rvm:
  - 2.0.0
  - 2.1.0
before_script:
  - sudo apt-get install -y unzip
  - curl -k -L -O https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip
  - unzip browsermob-proxy-2.1.4-bin.zip
  - export BROWSERMOB_PROXY_HOME=`pwd`/browsermob-proxy-2.1.4
  - sudo chmod +x $BROWSERMOB_PROXY_HOME/bin/browsermob-proxy
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
services:
  - xvfb
